- name: polylextest secrets
  openshift:
    state: latest
    resource: Secret
    name: "{{ polylex_secret_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      stringData:
        mongo-url: 'mongodb://{{ polylex_db_user }}:{{ polylex_db_password }}@{{ db_host }}.epfl.ch/{{ polylex_db_name }}'
        meteor-settings: '{{ wp_veritas_secrets.frontend.credentials.METEOR_SETTINGS }}'
      kind: Secret
      metadata:
        name: "{{ polylex_secret_name }}"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
