---
# vars file for epfl.polylex
polylex_app_name: polylex
polylex_svc_name: polylex
polylex_route_name: polylex
polylex_secret_name: "polylex"
polylex_cname: "{{ 'polylex-admin.epfl.ch' if openshift_namespace == 'wwp' else 'polylex.128.178.222.83.nip.io' }}"
polylex_deploy_name: polylex
polylex_image_version: '0.0.15'
polylex_image_tag: 'epflidevelop/polylex:{{ polylex_image_version }}'
polylex_db_name: "polylex"
polylex_db_user: "polylex"
polylex_db_password: "{{ lookup('env','POLYLEX_DB_PASSWORD_PROD') if openshift_namespace == 'wwp' else lookup('env','POLYLEX_DB_PASSWORD_TEST') }}"
meteor_settings_env: " {{ lookup('env','METEOR_SETTINGS') }}"
db_host: "{{ 'mongodb-svc-1' if openshift_namespace == 'wwp' else 'test-mongodb-svc-1' }}"